### ISSUE TITLE
Connection to node 0 (kafka/127.0.0.1:443) could not be established. Broker may not be available.

### ISSUE THREAD

**Issue by AchoArnold** [krisgeus/docker-kafka#11]
Hello,

I tried following the instructions on the readme  and when I reached the step to test the Kafka instance, when I run the command  `kafka-console-producer --broker-list kafka:9092 --topic test ` and input the message `"message1"`

Operating System: MacOS
Version: 10.14.6

Is there anything I'm doing wrong

**Comment by krisgeus** [comment]
you need to continue with the next part of the readme (in a separate terminal session preferably)

```
To consume this use the following in a separate terminal window

kafka-console-consumer --bootstrap-server kafka:9092 \
  --topic test \
  --from-beginning
```

The output should be:
  
`message1`

**Comment by AchoArnold** [comment]
When I do 

```
kafka-console-consumer --bootstrap-server kafka:9092 \
  --topic test \
  --from-beginning
```

on a separate window, I get a similar warning. 

This is a screenshot with both commands

<img width="1440" alt="Screenshot 2019-09-05 16 33 55" src="https://user-images.githubusercontent.com/4196457/64351677-050d2800-cffb-11e9-8ff2-8e8262a04837.png">

**Comment by krisgeus** [comment]
Ah. I think I know the reason.
kafka hostname is not known on your computer. You can add it to `/etc/hosts` like this:

```
127.0.0.1	kafka
```

**Comment by AchoArnold** [comment]
Hey @krisgeus 

I had already set `127.0.0.1	kafka` in the `/etc/hosts` file of my macbook

**Comment by krisgeus** [comment]
I found the error. It's in the docs ;-)
this is the correct command to start the docker container
```
docker run --rm -p 2181:2181 -p 9092:9092 -p 9093:9093   --env ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,INTERNAL://localhost:9093   --env LISTENERS=PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093   --env SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT   --env INTER_BROKER=INTERNAL   --env KAFKA_CREATE_TOPICS="test:36:1,krisgeus:12:1:compact"   --name kafka   krisgeus/docker-kafka
```

`ADVERTISED_LISTENERS=PLAINTEXT://kafka:443,INTERNAL://localhost:9093` specified port 443 which is not available. Changed it to 9092 and all is working as advertised (pun intended)

**Comment by krisgeus** [comment]
@AchoArnold Could you please check if this minor clarification in the docs helps solve this issue. If so I will merge this one to master. Thx

**Comment by AchoArnold** [comment]
Thanks very much, @krisgeus 

This new command fixed the issue 😄
