### ISSUE TITLE
Failed to set locale, defaulting to C, and no match for argument: supervisor

### ISSUE THREAD

**Issue by davehowell** [krisgeus/docker-kafka#13]
When I try to build this image, there are two issues

The locale is not set, it gives this warning `Failed to set locale, defaulting to C` and I fixed that as per this: https://github.com/CentOS/sig-cloud-instance-images/issues/71#issuecomment-538302151
It probably doesn't matter, as installing all those extra locales would make the image larger. 

The second issue is when trying to install supervisor, it gives this error:

```
Error: Unable to find a match
The command '/bin/sh -c yum update -y &&     yum install -y epel-release wget nc net-tools openssl krb5-workstation krb5-libs java which &&     yum install -y supervisor &&     wget -q         http://apache.mirrors.spacedump.net/kafka/"$KAFKA_VERSION"/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz         -O /tmp/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz &&     tar xfz /tmp/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz -C /opt &&     rm /tmp/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz &&     yum clean all' 
returned a non-zero code: 1
```

I found that the supervisor  package just isn't in the repo (anymore?).

I opened a shell into the base image

`docker run -it centos bash`

Then checked for the package
```
# yum install epel-release
# yum update
# yum info supervisor
Error: No matching Packages to list
```

If the package is not there, then the way to install it is with pip. I also found that `python-pip` is not in the repo, it's now called either `python3-pip` ( or the older v2)

This is what I ended up using which works

```
# Install Kafka, Zookeeper and other needed things
RUN yum update -y && \
    yum install -y epel-release wget nc net-tools openssl krb5-workstation krb5-libs java which && \
    yum install -y python3-pip && \
    pip3 install supervisor && \
    wget -q \
        http://apache.mirrors.spacedump.net/kafka/"$KAFKA_VERSION"/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz \
        -O /tmp/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz && \
    tar xfz /tmp/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz -C /opt && \
    rm /tmp/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz && \
    yum clean all
```

This doesn't run though, it can't find the `supervisord.conf` file in any of the default locations, perhaps that file was placed by the yum packaged version and is not when installing with pip, not sure yet.

**Comment by davehowell** [comment]
I got it running by adding a default config right before you expose the ports.
```RUN echo_supervisord_conf > /etc/supervisord.conf```

It seems OK for now, hopefully there was nothing magical that the yum packaged version did to modify that file. http://supervisord.org/installing.html#creating-a-configuration-file The docs mention that Ubuntu/Debian put it in another directory and modify the path, but if yum did anything like that it won't matter here. 

so far all OK...

**Comment by krisgeus** [comment]
Thx for this fix. I will prepare a PR. If you will be so kind to review and test it I would be grateful

**Comment by krisgeus** [comment]
@davehowell Please verify this PR. Thx in advance

**Comment by davehowell** [comment]
Looks good, I see you included the startup scripts dir. I guess that is the thing the yum packed version did for you.

I've tested it in the context of https://github.com/Fokko/divolte-kafka-druid-superset and it works well, thanks.
